name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: sanketlakhera/TODO-React-App@main
      - name: Update diagram
        uses: sanketlakhera/TODO-React-App@main
        with:
          excluded_paths: "ignore,.github"